module Autoflux
  # Agent implements the _Agent interface.
  interface _Agent
    def tool?: (String name) -> bool
    def tool: (String name) -> _Tool?
    def call: (memory: _Memory) -> event
  end
end
