module Autoflux
  type jsonString = String

  type invocation = {
    id: String,
    name: String,
    args: jsonString
  }

  type eventRole = "assistant" | "system" | "user" | "tool" | String
  type baseEvent = {
    role: eventRole,
    raw?: Hash[untyped, untyped]
  }
  type textEvent = baseEvent & {
    content: String
  }
  type invocationEvent = baseEvent & {
    invocations: Array[invocation]
  }
  type invocationResultEvent = textEvent & {
    invocation_id: String
  }

  type event = textEvent | invocationEvent | invocationResultEvent
end
