module Autoflux
  type eventType = :command | :agent | Symbol
  module EventType
    COMMAND: eventType & "command"
    AGENT: eventType & "agent"
  end

  type event = {
    id?: String,
    agent_id?: String,
    type: eventType,
    payload: ::_ToJson,
  }
end
