module Autoflux
  interface _Memory
    def data: () -> Array[untyped]
    def push: (untyped data) -> untyped
    def last: () -> untyped
  end

  # The Memory is a class to store the memory of the workflow.
  class Memory
    include _Memory

    @data: Array[untyped]
    @verbose: bool

    attr_reader verbose: bool

    # @rbs data: Array[Hash]
    def initialize: (?data: Array[untyped], ?verbose: bool) -> void
  end
end
