module Autoflux
  interface _Memory
    def data: () -> Array[event]
    def push: (event event) -> void
    def last: () -> event
  end

  # The Memory is a class to store the memory of the workflow.
  class Memory
    include _Memory

    @data: Array[event]
    @verbose: bool

    attr_reader verbose: bool

    # @rbs data: Array[Hash]
    def initialize: (?data: Array[event], ?verbose: bool) -> void
  end
end
