module Autoflux
  interface _Memory
    def data: () -> Array[_Event]
    def push: (_Event event) -> void
    def last: () -> _Event
  end

  # The Memory is a class to store the memory of the workflow.
  class Memory
    include _Memory

    @data: Array[_Event]
    @verbose: bool

    attr_reader verbose: bool

    # @rbs data: Array[Hash]
    def initialize: (?data: Array[_Event], ?verbose: bool) -> void
  end
end
