module Autoflux
  # The Stdio is a class to represent the standard input/output.
  class Stdio < IO
    @input: untyped

    @output: untyped

    @prompt: untyped

    attr_accessor prompt: untyped

    # @rbs input: IO
    # @rbs output: IO
    def initialize: (?input: untyped, ?output: untyped, ?prompt: untyped?) -> void

    def read: () -> untyped

    # @rbs data: String
    def write: (untyped data) -> untyped
  end
end
