module Autoflux
  # The Stdio is a class to represent the standard input/output.
  class Stdio
    include _IO

    @input: ::IO
    @output: ::IO
    @prompt: String?

    attr_accessor prompt: String?

    def initialize: (?input: IO, ?output: IO, ?prompt: String?) -> void
  end
end
