module Autoflux
  interface _Step
    def to_s: () -> String
    def call: (workflow: Workflow) -> untyped
  end

  module Step
    class Start
      include Autoflux::_Step
    end

    class Stop
      include Autoflux::_Step
    end

    class Agent
      include Autoflux::_Step
    end

    class Command
      include Autoflux::_Step
    end
  end
end
