module Autoflux
  # The workflow is a state machine to manage the flow of agentic AI.
  class Workflow
    include Enumerable[Workflow]

    @id: String
    @agent: _Agent
    @agents: Array[_Agent]
    @io: _IO
    @step: _Step

    def self.next_id: () -> String

    attr_reader id: String
    attr_reader agent: _Agent
    attr_reader agents: Array[_Agent]
    attr_reader io: _IO

    def initialize: (io: _IO, ?agent: _Agent, ?agents: Array[_Agent], ?id: String?, ?step: _Step) -> void
    def each: { (Workflow) -> void } -> void
    def run: () ?{ (Workflow) -> void } -> void
    def switch_agent: (String name) -> _Agent
    def stop: () -> void
    def step: () -> _Step
    def to_h: () -> { id: String, step: String }
  end
end
