module Autoflux
  module Step
    # The Step::Base is abstract class to represent the interface of the state
    class Base
      # @rbs workflow: Workflow
      def call: (**untyped) -> untyped
    end
  end
end
