module Autoflux
  module Step
    # The Tool state is used to call the tools provided by the agent.
    class Tool < Base
      def call: (workflow: untyped) -> untyped

      def run: (workflow: untyped, tool: untyped) -> untyped
    end
  end
end
